In [20]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=1, suppress=True, linewidth=90)

rpdc = np.loadtxt('asym_coups_cp43_reppert2008.txt')
rpdc += rpdc.transpose()

rtresp = np.loadtxt('asym_coups_cp47_reppert2010.txt')
rtresp += rtresp.transpose()

tpdc = np.loadtxt('2AXTpdc_coups.txt')
ttresp = np.loadtxt('3BZ1tresp_coups.txt')



print('Max Abs TrESP Error:', np.max(np.abs(rtresp - ttresp)))
print('Max Abs PDC Error:', np.max(np.abs(rpdc - tpdc)))

print(rpdc - tpdc)

Max Abs TrESP Error: 0.498
Max Abs PDC Error: 0.1599999999999966
[[ 0.  -0.   0.  -0.  -0.  -0.1 -0.  -0.   0.   0.   0.  -0.   0. ]
 [-0.   0.   0.1 -0.2 -0.   0.   0.   0.  -0.  -0.1  0.  -0.   0. ]
 [ 0.   0.1  0.  -0.  -0.  -0.  -0.   0.  -0.  -0.   0.  -0.1  0. ]
 [-0.  -0.2 -0.   0.  -0.  -0.  -0.  -0.   0.  -0.  -0.  -0.  -0. ]
 [-0.  -0.  -0.  -0.   0.   0.   0.1  0.  -0.1  0.  -0.1  0.   0.1]
 [-0.1  0.  -0.  -0.   0.   0.  -0.1  0.   0.   0.  -0.   0.   0. ]
 [-0.   0.  -0.  -0.   0.1 -0.1  0.  -0.  -0.1  0.  -0.  -0.  -0. ]
 [-0.   0.   0.  -0.   0.   0.  -0.   0.  -0.1 -0.1 -0.1 -0.  -0. ]
 [ 0.  -0.  -0.   0.  -0.1  0.  -0.1 -0.1  0.   0.1 -0.2 -0.1 -0. ]
 [ 0.  -0.1 -0.  -0.   0.   0.   0.  -0.1  0.1  0.   0.1  0.  -0. ]
 [ 0.   0.   0.  -0.  -0.1 -0.  -0.  -0.1 -0.2  0.1  0.  -0.  -0.1]
 [-0.  -0.  -0.1 -0.   0.   0.  -0.  -0.  -0.1  0.  -0.   0.   0.1]
 [ 0.   0.   0.  -0.   0.1  0.  -0.  -0.  -0.  -0.  -0.1  0.1  0. ]]
